package gui.dialogosCRUD;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Cancion;


public class CancionDialogo extends javax.swing.JDialog {

    /**
     * Creates new form Cancion
     */
    public CancionDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static final boolean CREACION = true;
    public static final boolean EDICION = false;
    private boolean tipo;
    private Cancion can;
    
    public CancionDialogo(java.awt.Frame parent, boolean modal, boolean tipo, Cancion cancion) {
        super(parent, modal);
        initComponents();
        
        this.tipo = tipo;
        
        if (this.tipo == CREACION) {
            setTitle("Creación de canción");
            botonEnviar.setText("Crear canción");
        } else {
            setTitle("Edición de canción");
            this.can = cancion;
            botonEnviar.setText("Editar canción");
            campoCancion.setText(can.getTitulo());
            campoAutor.setText(can.getAutor());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        campoCancion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoAutor = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creación de canción");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Título de la canción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 5, 25);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        getContentPane().add(campoCancion, gridBagConstraints);

        jLabel2.setText("Nombre del autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(15, 25, 5, 25);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        getContentPane().add(campoAutor, gridBagConstraints);

        botonEnviar.setText("Crear canción");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.insets = new java.awt.Insets(15, 25, 25, 25);
        getContentPane().add(botonEnviar, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        if (campoCancion.getText().length() < 3 || campoCancion.getText().length() >= 20) {
            JOptionPane.showMessageDialog(this, "Por favor, escriba un título con una longitud mayor que tres caracteres y menor que veinte caracteres.");
        } else {
            if (tipo == CREACION) {
            logica.LogicaConexion.getCancionController().create(new objetos.Cancion(campoCancion.getText(), campoAutor.getText()));
        } else {
            try {
                can.setTitulo(campoCancion.getText());
                can.setAutor(campoAutor.getText());
                logica.LogicaConexion.getCancionController().edit(can);
            } catch (Exception ex) {
                Logger.getLogger(UsuarioDialogo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();
        logica.logicaDatos.actualizarDatos();
        }
    }//GEN-LAST:event_botonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancionDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancionDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancionDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancionDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CancionDialogo dialog = new CancionDialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JTextField campoCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
